import { REGISTRY_ITEM_FILTERS } from "./filters";
import { REGISTRY_ITEM_GET } from "./get";
import { REGISTRY_ITEM_LIST } from "./list";
import { REGISTRY_ITEM_SEARCH } from "./search";
import { REGISTRY_ITEM_VERSIONS } from "./versions";
import {
  COLLECTION_REGISTRY_APP_FILTERS,
  COLLECTION_REGISTRY_APP_GET,
  COLLECTION_REGISTRY_APP_LIST,
  COLLECTION_REGISTRY_APP_VERSIONS,
} from "./collection-registry-app";

export const tools = [
  COLLECTION_REGISTRY_APP_LIST,
  COLLECTION_REGISTRY_APP_GET,
  COLLECTION_REGISTRY_APP_VERSIONS,
  COLLECTION_REGISTRY_APP_FILTERS,
  REGISTRY_ITEM_LIST,
  REGISTRY_ITEM_SEARCH,
  REGISTRY_ITEM_GET,
  REGISTRY_ITEM_VERSIONS,
  REGISTRY_ITEM_FILTERS,
];
