{{- if and (eq (lower (default "sqlite" .Values.database.engine)) "postgresql") .Values.database.caCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-deco-studio.fullname" . }}-ca-cert
  labels:
    {{- include "chart-deco-studio.labels" . | nindent 4 }}
data:
  ca-cert.pem: |
{{ .Values.database.caCert | indent 4 }}
{{- end }}

