// This file was auto-generated by @decocms/typegen. Do not edit manually.
// Regenerate with: bunx @decocms/typegen --mcp <id> --key <key> --output <file>

import { createStudioClient } from "@decocms/typegen";

export interface Tools {}

export const client = createStudioClient<Tools>({
  mcpId: "vir_tFfcM9madOxKe0krs7XoR",
  apiKey: process.env.STUDIO_API_KEY ?? process.env.MESH_API_KEY,
  baseUrl: process.env.STUDIO_BASE_URL ?? process.env.MESH_BASE_URL,
});
