{{- if and .Values.dbosConductor .Values.dbosConductor.enabled .Values.dbosConductor.key (not .Values.dbosConductor.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-deco-studio.fullname" . }}-dbos-conductor
  labels:
    {{- include "chart-deco-studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  DBOS_CONDUCTOR_KEY: {{ .Values.dbosConductor.key | quote }}
{{- end }}
