{{- if not (and .Values.argoRollouts .Values.argoRollouts.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-deco-studio.fullname" . }}
  labels:
    {{- include "chart-deco-studio.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ include "chart-deco-studio.deploymentStrategy" . }}
    {{- $strategyType := include "chart-deco-studio.deploymentStrategy" . }}
    {{- if eq $strategyType "RollingUpdate" }}
    rollingUpdate:
      {{- if and .Values.strategy .Values.strategy.rollingUpdate }}
      {{- toYaml .Values.strategy.rollingUpdate | nindent 6 }}
      {{- else }}
      maxSurge: 1
      maxUnavailable: 0
      {{- end }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "chart-deco-studio.selectorLabels" . | nindent 6 }}
  template:
    {{- include "chart-deco-studio.podTemplate" . | nindent 4 }}
{{- end }}
