{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart-deco-studio.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.provider.aws.region }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "chart-deco-studio.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart-deco-studio.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ include "chart-deco-studio.fullname" . }}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretPath }}
{{- end }}
