{{- if not .Values.secret.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-deco-studio.fullname" . }}-secrets
  labels:
    {{- include "chart-deco-studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  BETTER_AUTH_SECRET: {{ .Values.secret.BETTER_AUTH_SECRET | quote }}
  ENCRYPTION_KEY: {{ .Values.secret.ENCRYPTION_KEY | default "" | quote }}
  {{- if eq (lower (default "sqlite" .Values.database.engine)) "postgresql" }}
  DATABASE_URL: {{ include "chart-deco-studio.databaseUrl" . | trim | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_GOOGLE_CLIENT_ID }}
  AUTH_GOOGLE_CLIENT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_GOOGLE_CLIENT_SECRET }}
  AUTH_GOOGLE_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_GITHUB_CLIENT_ID }}
  AUTH_GITHUB_CLIENT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_GITHUB_CLIENT_SECRET }}
  AUTH_GITHUB_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_RESEND_API_KEY }}
  AUTH_RESEND_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_RESEND_FROM_EMAIL }}
  AUTH_RESEND_FROM_EMAIL: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_SENDGRID_API_KEY }}
  AUTH_SENDGRID_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_SENDGRID_FROM_EMAIL }}
  AUTH_SENDGRID_FROM_EMAIL: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_SSO_DOMAIN }}
  AUTH_SSO_DOMAIN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_SSO_MS_TENANT_ID }}
  AUTH_SSO_MS_TENANT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_SSO_MS_CLIENT_ID }}
  AUTH_SSO_MS_CLIENT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_SSO_MS_CLIENT_SECRET }}
  AUTH_SSO_MS_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_SSO_GOOGLE_CLIENT_ID }}
  AUTH_SSO_GOOGLE_CLIENT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.AUTH_SSO_GOOGLE_CLIENT_SECRET }}
  AUTH_SSO_GOOGLE_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
{{- end }}
