{{- if and .Values.serviceAccount .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart-deco-studio.serviceAccountName" . }}
  labels:
    {{- include "chart-deco-studio.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- if .Values.serviceAccount.annotations }}
  {{- $annotations = merge $annotations .Values.serviceAccount.annotations }}
  {{- end }}
  {{- if and .Values.s3Sync .Values.s3Sync.roleArn }}
  {{- $_ := set $annotations "eks.amazonaws.com/role-arn" .Values.s3Sync.roleArn }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- end }}
