{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-deco-studio.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "chart-deco-studio.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "chart-deco-studio.chart" . }}
spec:
  type: {{ .Values.web.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.web.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "chart-deco-studio.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
