import { compile } from "json-schema-to-typescript";
import { format } from "prettier";

export interface ToolDefinition {
  name: string;
  inputSchema: object;
  outputSchema?: object;
}

export interface GenerateOptions {
  mcpId: string;
  tools: ToolDefinition[];
}

const BANNER = `// This file was auto-generated by @decocms/typegen. Do not edit manually.
// Regenerate with: bunx @decocms/typegen --mcp <id> --key <key> --output <file>
`;

const PRETTIER_CONFIG = {
  parser: "typescript" as const,
  printWidth: 80,
  singleQuote: false,
  trailingComma: "all" as const,
  semi: true,
};

async function schemaToTs(schema: object, typeName: string): Promise<string> {
  const raw = await compile(schema as never, typeName, {
    bannerComment: "",
    additionalProperties: false,
  });
  // compile() emits `export interface TypeName { ... }` or `export type TypeName = ...`
  // We only want the body, so strip the export declaration wrapper
  return raw
    .replace(/^export\s+(interface|type)\s+\S+\s*(=\s*)?/m, "")
    .replace(/;\s*$/, "")
    .trim();
}

export async function generateClientCode(
  opts: GenerateOptions,
): Promise<string> {
  const { mcpId, tools } = opts;

  const toolEntries: string[] = [];

  for (const tool of tools) {
    const inputType = await schemaToTs(tool.inputSchema, `${tool.name}Input`);
    const outputType = tool.outputSchema
      ? await schemaToTs(tool.outputSchema, `${tool.name}Output`)
      : "unknown";

    toolEntries.push(
      `  ${tool.name}: {\n    input: ${inputType};\n    output: ${outputType};\n  };`,
    );
  }

  const toolsInterface =
    tools.length === 0
      ? "export interface Tools {}"
      : `export interface Tools {\n${toolEntries.join("\n")}\n}`;

  const code = `${BANNER}
import { createMeshClient } from "@decocms/typegen";

${toolsInterface}

export const client = createMeshClient<Tools>({
  mcpId: "${mcpId}",
  apiKey: process.env.MESH_API_KEY,
  baseUrl: process.env.MESH_BASE_URL,
});
`;

  return format(code, PRETTIER_CONFIG);
}
