import { compile } from "json-schema-to-typescript";
import { format } from "prettier";

export interface ToolDefinition {
  name: string;
  inputSchema: object;
  outputSchema?: object;
}

export interface GenerateOptions {
  mcpId: string;
  tools: ToolDefinition[];
}

const BANNER = `// This file was auto-generated by @decocms/typegen. Do not edit manually.
// Regenerate with: bunx @decocms/typegen --mcp <id> --key <key> --output <file>
`;

const PRETTIER_CONFIG = {
  parser: "typescript" as const,
  printWidth: 80,
  singleQuote: false,
  trailingComma: "all" as const,
  semi: true,
};

async function schemaToTs(schema: object, typeName: string): Promise<string> {
  const raw = await compile(schema as never, typeName, {
    bannerComment: "",
    additionalProperties: false,
  });

  // compile() may emit helper type aliases alongside the primary declaration, e.g.:
  //   export interface PrimaryInput { query?: Query; }
  //   export type Query = string | null;
  // Collect these aliases so we can inline them.
  const aliases = new Map<string, string>();
  const aliasRe = /^export\s+type\s+(\w+)\s*=\s*([^{][^;]*);$/gm;
  for (const m of raw.matchAll(aliasRe)) {
    if (m[1] !== typeName) aliases.set(m[1], m[2].trim());
  }

  // Strip the primary declaration header
  let result = raw
    .replace(/^export\s+(interface|type)\s+\S+\s*(=\s*)?/m, "")
    .replace(/;\s*$/, "")
    .trim();

  // Remove extra type alias declarations (and any preceding JSDoc comments)
  result = result
    .replace(
      /\/\*\*[\s\S]*?\*\/\s*\nexport\s+type\s+\w+\s*=\s*[^{][^;]*;/gm,
      "",
    )
    .replace(/^export\s+type\s+\w+\s*=\s*[^{][^;]*;$/gm, "")
    .trim();

  // Inline type aliases into the result
  for (const [name, body] of aliases) {
    result = result.replace(new RegExp(`\\b${name}\\b`, "g"), body);
  }

  return result;
}

export async function generateClientCode(
  opts: GenerateOptions,
): Promise<string> {
  const { mcpId, tools } = opts;

  const toolEntries: string[] = [];

  for (const tool of tools) {
    const inputType = await schemaToTs(tool.inputSchema, `${tool.name}Input`);
    const outputType = tool.outputSchema
      ? await schemaToTs(tool.outputSchema, `${tool.name}Output`)
      : "unknown";

    toolEntries.push(
      `  ${tool.name}: {\n    input: ${inputType};\n    output: ${outputType};\n  };`,
    );
  }

  const toolsInterface =
    tools.length === 0
      ? "export interface Tools {}"
      : `export interface Tools {\n${toolEntries.join("\n")}\n}`;

  const code = `${BANNER}
import { createMeshClient } from "@decocms/typegen";

${toolsInterface}

export const client = createMeshClient<Tools>({
  mcpId: "${mcpId}",
  apiKey: process.env.MESH_API_KEY,
  baseUrl: process.env.MESH_BASE_URL,
});
`;

  return format(code, PRETTIER_CONFIG);
}
