/**
 * Branch-name generator used as a fallback when SANDBOX_START is invoked without
 * an explicit branch. The word lists were lifted out of daemon.ts so the
 * orchestrator — not the sandbox — decides the branch name and can persist
 * it to sandboxMap before the daemon ever sees it.
 *
 * Format: `<greek-letter>-<constellation-genitive>` — mirrors real Bayer
 * designations for stars (e.g. α Centauri → `alpha-centauri`, β Pictoris →
 * `beta-pictoris`). Only single-word constellation genitives are used so the
 * result is always a clean two-token, hyphen-joined git ref.
 */

const GREEK_LETTERS: readonly string[] = [
  "alpha",
  "beta",
  "gamma",
  "delta",
  "epsilon",
  "zeta",
  "eta",
  "theta",
  "iota",
  "kappa",
  "lambda",
  "mu",
  "nu",
  "xi",
  "omicron",
  "pi",
  "rho",
  "sigma",
  "tau",
  "upsilon",
  "phi",
  "chi",
  "psi",
  "omega",
];

const CONSTELLATIONS: readonly string[] = [
  "andromedae",
  "antliae",
  "apodis",
  "aquarii",
  "aquilae",
  "arae",
  "arietis",
  "aurigae",
  "bootis",
  "caeli",
  "camelopardalis",
  "cancri",
  "capricorni",
  "carinae",
  "cassiopeiae",
  "centauri",
  "cephei",
  "ceti",
  "chamaeleontis",
  "circini",
  "columbae",
  "corvi",
  "crateris",
  "crucis",
  "cygni",
  "delphini",
  "doradus",
  "draconis",
  "equulei",
  "eridani",
  "fornacis",
  "geminorum",
  "gruis",
  "herculis",
  "horologii",
  "hydrae",
  "hydri",
  "indi",
  "lacertae",
  "leonis",
  "leporis",
  "librae",
  "lupi",
  "lyncis",
  "lyrae",
  "mensae",
  "microscopii",
  "monocerotis",
  "muscae",
  "normae",
  "octantis",
  "ophiuchi",
  "orionis",
  "pavonis",
  "pegasi",
  "persei",
  "phoenicis",
  "pictoris",
  "piscium",
  "puppis",
  "pyxidis",
  "reticuli",
  "sagittae",
  "sagittarii",
  "scorpii",
  "sculptoris",
  "scuti",
  "serpentis",
  "sextantis",
  "tauri",
  "telescopii",
  "trianguli",
  "tucanae",
  "velorum",
  "virginis",
  "volantis",
  "vulpeculae",
];

export function generateBranchName(): string {
  const greek = GREEK_LETTERS[Math.floor(Math.random() * GREEK_LETTERS.length)];
  const constellation =
    CONSTELLATIONS[Math.floor(Math.random() * CONSTELLATIONS.length)];
  return `${greek}-${constellation}`;
}
