// Generated by packages/sandbox/controller-go/cmd/tsgen from the SandboxVariant CRD.
// Do not edit; run `go generate ./...` in packages/sandbox/controller-go.

export const API_VERSION = "sandbox.deco.cx/v1alpha1";
export const KIND = "SandboxVariant";

export interface SandboxVariantSpec {
  /** The base image tag the variant was built FROM, so skew against status.defaultTemplateTag is readable from the object. */
  baseTag: string;
  /** The default SandboxTemplate this variant is copied from. Its `-medium` sibling is the base of the variant's medium template. */
  baseTemplate: string;
  image: {
    repository: string;
    tag: string;
  };
  /** Replace the base template's, when set. */
  nodeSelector?: Record<string, string>;
  /** Deep-merged over each size's own `sandbox` container resources. */
  resources?: {
    /** Claims lists the names of resources, defined in spec.resourceClaims, that are used by this container. This field depends on the DynamicResourceAllocation feature gate. This field is immutable. It can only be set for containers. */
    claims?: Array<{
      /** Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container. */
      name: string;
      /** Request is the name chosen for a request in the referenced claim. If empty, everything from the claim is made available, otherwise only the result of this request. */
      request?: string;
    }>;
    /** Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ */
    limits?: Record<string, number | string>;
    /** Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ */
    requests?: Record<string, number | string>;
  };
  tolerations?: Array<{
    /** Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute. */
    effect?: string;
    /** Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys. */
    key?: string;
    /** Operator represents a key's relationship to the value. Valid operators are Exists, Equal, Lt, and Gt. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category. Lt and Gt perform numeric comparisons (requires feature gate TaintTolerationComparisonOperators). */
    operator?: string;
    /** TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system. */
    tolerationSeconds?: number;
    /** Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string. */
    value?: string;
  }>;
  /** emptyDir sizeLimits by volume name, merged over the base template's. */
  volumeSizes?: Record<string, number | string>;
  warmPool?: {
    mediumSize?: number;
    size?: number;
  };
}

export interface SandboxVariantStatus {
  conditions?: Array<{
    /** lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed. If that is not known, then using the time when the API field changed is acceptable. */
    lastTransitionTime: string;
    /** message is a human readable message indicating details about the transition. This may be an empty string. */
    message: string;
    /** observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance. */
    observedGeneration?: number;
    /** reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty. */
    reason: string;
    /** status of the condition, one of True, False, Unknown. */
    status: "True" | "False" | "Unknown";
    /** type of condition in CamelCase or in foo.example.com/CamelCase. */
    type: string;
  }>;
  /** The base template's sandbox image tag. */
  defaultTemplateTag?: string;
  observedGeneration?: number;
  templates?: Array<string>;
}

export interface SandboxVariant {
  apiVersion: typeof API_VERSION;
  kind: typeof KIND;
  metadata: {
    name: string;
    namespace?: string;
    labels?: Record<string, string>;
    annotations?: Record<string, string>;
  };
  spec: SandboxVariantSpec;
  status?: SandboxVariantStatus;
}
