// Generated by packages/sandbox/controller-go/cmd/tsgen from the controller's protocol package.
// Do not edit; run `go generate ./...` in packages/sandbox/controller-go.

/**
 * Package protocol is the controller's HTTP API: what Studio sends and reads,
 * and the callbacks the controller makes into Studio. The TypeScript types in
 * packages/sandbox/controller-types/sandbox-api.ts are generated from this
 * file (cmd/tsgen), so a field changed here breaks Studio's build.
 *
 * Field rules the generator relies on: `omitempty` means optional in
 * TypeScript; a pointer without it is `T | null`.
 */

/** POST: EnsureRequest → EnsureResponse. */
export const PathSandboxes = "/sandboxes";

/**
 * GET → StatusResponse (`?resurrect=1` to re-provision a reaped sandbox);
 * DELETE → 204, or 202 DrainingResponse.
 */
export const PathSandbox = "/sandboxes/{handle}";

/** PATCH: LifetimeRequest → 204. */
export const PathLifetime = "/sandboxes/{handle}/lifetime";

/** POST: CredentialsRequest → 204. */
export const PathCredentials = "/sandboxes/{handle}/credentials";

/** GET → text/event-stream of Phase. */
export const PathEvents = "/sandboxes/{handle}/events";

/** GET → ImagesResponse. */
export const PathImages = "/images";

/** GET → RuntimesResponse. */
export const PathRuntimes = "/runtimes";

/**
 * GET → CapacityResponse. `?sandboxImage=<name>` judges the nodes that
 * image's variant schedules onto instead of the default image's.
 */
export const PathCapacity = "/capacity";

/** POST: TenantPoolsPushRequest → TenantPoolsPushResponse. */
export const PathTenantPoolsPush = "/tenant-pools/push";

/** GET → HealthzResponse. Needs a client certificate like every other route. */
export const PathHealthz = "/healthz";

/**
 * SandboxID is Studio's tenant-scoped identity for a sandbox. The controller
 * never parses ProjectRef: it is an opaque key.
 */
export interface SandboxID {
  userId: string;
  projectRef: string;
}

/**
 * Capability names an optional provider behaviour, declared as data so Studio
 * branches on it instead of on a runtime's name.
 */
export type Capability =
  /** A preview URL is served for the sandbox. */
  | "preview"
  /** GET /sandboxes/:handle/events reports the pre-ready phases, not only "ready". */
  | "lifecycle-phases"
  /** Claims may bind prewarmed pods. */
  | "warm-pool"
  /** lastTermination can say why the sandbox stopped (OOM, eviction). */
  | "termination-reason"
  /** PATCH /sandboxes/:handle/lifetime moves shutdown. */
  | "ttl-extend"
  /** The runtime answers the capacity probe; without it, it always admits. */
  | "capacity";

/**
 * Purpose decides the template size and pool; it survives into the persisted
 * options a resurrected sandbox is rebuilt from.
 */
export type Purpose = "interactive" | "harness-run";

export type WorkloadRuntime = "node" | "bun" | "deno";

export type PackageManager = "npm" | "pnpm" | "yarn" | "bun" | "deno";

/**
 * Workload is what the daemon runs once the checkout lands. Absent means no
 * dev server is requested (the daemon may still autodetect one unless
 * cloneOnly is set).
 */
export interface Workload {
  runtime: WorkloadRuntime;
  packageManager: PackageManager;
  /** User-pinned dev port; the default (3000) when absent. */
  devPort?: number;
  /** Subdirectory holding the package manager manifest (e.g. `apps/web`). */
  packageManagerPath?: string;
}

/**
 * SubmoduleCredential is a per-host PAT for a private submodule the clone
 * token cannot reach.
 */
export interface SubmoduleCredential {
  host: string;
  token: string;
}

/**
 * EnsureRepo is one repository a sandbox checks out: the primary (`repo`) or
 * a secondary (`extraRepos`).
 */
export interface EnsureRepo {
  /**
   * May embed a short-lived credential as userinfo. Studio passes a freshly
   * minted URL on every ensure; the controller re-mints it for long-lived
   * sandboxes through the clone-url callback.
   */
  cloneUrl: string;
  /** Connection the credential is minted from; echoed back on the callback. */
  connectionId?: string;
  /**
   * First-class repository the credential is minted from; echoed back on the
   * callback. Set instead of connectionId for Studio-owned credentials.
   */
  repositoryId?: string;
  userName: string;
  userEmail: string;
  branch?: string;
  /** Human-readable label; no functional effect. */
  displayName?: string;
  submoduleCredentials?: Array<SubmoduleCredential>;
  /** Directory for a secondary checkout. A secondary without one is dropped. */
  directoryName?: string;
}

/**
 * Tenant is cost-attribution identity: IDs become pod labels, the rest
 * annotations.
 */
export interface Tenant {
  orgId: string;
  userId: string;
  orgSlug?: string;
  orgName?: string;
  userEmail?: string;
  userName?: string;
}

/** EnsureOptions is what Studio's ensure() takes. */
export interface EnsureOptions {
  /** Defaults to interactive. */
  purpose?: Purpose;
  /**
   * The image the primary repository asked for; absent or "default" is the
   * base image. A preference: a runtime that cannot serve it degrades to the
   * default and reports it in the response's image.served.
   */
  sandboxImage?: string;
  /**
   * The synthetic isolation key, recorded as the claim's git-branch
   * annotation. Not an identity input.
   */
  branch?: string;
  repo?: EnsureRepo;
  /** Checkouts beside repo; ignored without a repo. */
  extraRepos?: Array<EnsureRepo>;
  workload?: Workload;
  /** Prepare the checkout only: no install, no dev server. */
  cloneOnly?: boolean;
  /** Frozen for the sandbox's lifetime. */
  env?: Record<string, string>;
  tenant?: Tenant;
  /**
   * org-fs mount config (a JSON OrgFsMountConfig) relayed to the pod's
   * sidecar.
   */
  orgFsConfigJson?: string;
}

/** EnsureRequest is POST /sandboxes. */
export interface EnsureRequest {
  id: SandboxID;
  /**
   * Studio-derived claim name, so preview routing can recompute it without a
   * database read. The controller never derives one; it rejects a handle
   * recorded for another id.
   */
  handle: string;
  opts?: EnsureOptions;
  /**
   * A named runtime is a hard constraint: unavailable, incapable or full is
   * a 503, never a silent placement elsewhere, unless allowFallback.
   */
  runtime?: string;
  requires?: Array<Capability>;
  allowFallback?: boolean;
}

/**
 * Daemon is where the sandbox's daemon is and the bearer that opens it. The
 * controller never carries daemon bytes.
 */
export interface Daemon {
  url: string;
  token: string;
}

/**
 * Image is the image a sandbox asked for and the one it got. They differ when
 * the cluster lacks the variant: the sandbox runs on the default image.
 */
export interface Image {
  requested: string;
  served: string;
}

/** EnsureResponse returns once the daemon is healthy and configured. */
export interface EnsureResponse {
  handle: string;
  workdir: string;
  previewUrl: string | null;
  daemon: Daemon;
  runtime: string;
  image: Image;
  /**
   * The pod came from the tenant's warm pool: cloned, installed and serving
   * already. False for a cold pod and for a resumed or adopted sandbox.
   */
  warmPoolAdopted: boolean;
  capabilities: Array<Capability>;
  /**
   * Set when the handle already lived on another runtime than the one
   * requested; the live sandbox is returned unchanged.
   */
  runtimeMismatch?: string;
}

/**
 * PodTermination is how the infrastructure, not the daemon, saw a sandbox
 * stop. An OOM kill exists only here.
 */
export interface PodTermination {
  /** Kubelet terminated.reason, e.g. OOMKilled, Error, Evicted. */
  reason: string;
  oomKilled: boolean;
  exitCode?: number;
  /** The limit that was hit, as Kubernetes spells it (`4Gi`). */
  memoryLimit?: string;
  /** The kubelet's eviction message when reason is Evicted, verbatim. */
  evictionMessage?: string;
}

/**
 * StatusResponse is GET /sandboxes/:handle. With `?resurrect=1` a sandbox
 * whose claim is gone is re-provisioned from its persisted options first.
 */
export interface StatusResponse {
  handle: string;
  alive: boolean;
  previewUrl: string | null;
  daemon: Daemon | null;
  runtime: string;
  image: Image | null;
  capabilities: Array<Capability>;
  lastTermination: PodTermination | null;
}

/**
 * DrainingResponse is DELETE /sandboxes/:handle's 202: the claim is not gone
 * yet. It means retry, not success; a caller rebinding must not POST on it.
 */
export interface DrainingResponse {
  state: string;
}

/**
 * LifetimeRequest is PATCH /sandboxes/:handle/lifetime. Exactly one field:
 * extendToIdleWindow only moves shutdown later, graceMs only earlier.
 */
export interface LifetimeRequest {
  extendToIdleWindow?: boolean;
  graceMs?: number;
}

/**
 * CredentialsRequest is POST /sandboxes/:handle/credentials: rotate the
 * primary checkout's clone credential in place (same repository, new token).
 */
export interface CredentialsRequest {
  cloneUrl: string;
}

/**
 * TenantPoolsPushRequest is POST /tenant-pools/push: a GitHub push landed, so
 * the tenant pools warmed on that repo and branch refresh their unbound pods
 * now instead of at their next periodic refresh.
 */
export interface TenantPoolsPushRequest {
  /** `owner/name`, case-insensitive. */
  repo: string;
  /** The pushed ref, e.g. `refs/heads/main`. */
  ref: string;
}

/** TenantPoolsPushResponse names the pools the push marked stale. */
export interface TenantPoolsPushResponse {
  pools: Array<string>;
}

/**
 * PhaseKind is one pre-ready lifecycle phase. Runtimes without an equivalent
 * emit a single "ready".
 */
export type PhaseKind =
  | "claiming"
  | "waiting-for-capacity"
  | "pulling-image"
  | "starting-container"
  | "warming-daemon"
  | "ready"
  | "failed";

export type FailureReason =
  | "image-pull-backoff"
  | "crash-loop-backoff"
  | "scheduling-timeout";

/**
 * Phase is one event on GET /sandboxes/:handle/events (`data: <json>`). The
 * stream ends after "ready" or "failed".
 */
export interface Phase {
  kind: PhaseKind;
  /** Epoch ms the watch started; absent on terminal phases. */
  since?: number;
  message?: string;
  /** Karpenter nodeclaim being provisioned, on waiting-for-capacity. */
  nodeClaim?: string;
  /** Set on failed. */
  reason?: FailureReason;
}

/** ImageInfo is one variant a runtime can serve. */
export interface ImageInfo {
  /** The value Studio stores in repositories.sandbox_image. */
  name: string;
  /** Base image tag the variant was built from. */
  baseTag?: string;
  /** Tag the default template runs now; differs from baseTag on skew. */
  defaultTemplateTag?: string;
}

export interface RuntimeImages {
  runtime: string;
  images: Array<ImageInfo>;
}

/** ImagesResponse is GET /images. */
export interface ImagesResponse {
  runtimes: Array<RuntimeImages>;
}

/** Capacity is "nothing is currently unplaceable", never a reservation. */
export interface Capacity {
  schedulable: boolean;
  /** RFC 3339. */
  observedAt: string;
}

/** RuntimeInfo is one entry of GET /runtimes. */
export interface RuntimeInfo {
  name: string;
  available: boolean;
  /** Why it is unavailable. */
  reason?: string;
  priority: number;
  capacity?: Capacity;
  capabilities: Array<Capability>;
}

/** RuntimesResponse is GET /runtimes. */
export interface RuntimesResponse {
  runtimes: Array<RuntimeInfo>;
}

/**
 * CapacityResponse is GET /capacity: Studio's admission gate. True when any
 * available runtime has room.
 */
export interface CapacityResponse {
  schedulable: boolean;
}

/** HealthzResponse is GET /healthz. */
export interface HealthzResponse {
  ok: boolean;
}

/**
 * ErrorCode says what failed, so Studio can word and retry it without
 * matching messages.
 */
export type ErrorCode =
  /** The request failed validation; message says which field. */
  | "bad-request"
  /** No sandbox is recorded under the handle. */
  | "unknown-handle"
  /** The handle is recorded for another sandbox id. */
  | "handle-conflict"
  /** The recorded runtime is not in this build: the sandbox is left alone. */
  | "runtime-unreachable"
  /** Nothing could place the sandbox (503); reasons has one entry per runtime. */
  | "no-runtime"
  /**
   * The pod's daemon rejected the bootstrap handshake; the claim was
   * released and a retry gets a different pod. status is the daemon's.
   */
  | "bootstrap-rejected"
  /**
   * The claim reached a terminal failure (image pull, crash loop,
   * unschedulable) and was released.
   */
  | "claim-failed"
  /** The claim stopped making progress and was released. */
  | "claim-stalled"
  /** The daemon of a live sandbox refused or failed a control call. */
  | "daemon-error"
  | "internal";

/** ErrorResponse is every non-2xx body. */
export interface ErrorResponse {
  error: string;
  code: ErrorCode;
  /** Per-runtime placement reasons, on no-runtime. */
  reasons?: Record<string, string>;
  /** The daemon's HTTP status, on bootstrap-rejected and daemon-error. */
  status?: number;
}

/**
 * CloneURLPath is the controller's credential callback into Studio, over mTLS.
 * Studio must verify that the connection or repository belongs to a sandbox
 * row or a configured warm pool before minting: an unverified endpoint mints
 * a token for any connection in the deployment.
 */
export const CloneURLPath = "/api/_sandbox-controller/clone-url";

export interface CloneURLRequest {
  connectionId?: string;
  repositoryId?: string;
  cloneUrl: string;
  /** Re-mint when the current token has less than this much life left. */
  bufferMs?: number;
}

export interface CloneURLResponse {
  /** Null when Studio cannot mint; the controller keeps the URL it has. */
  cloneUrl: string | null;
}

/**
 * OrgFsConfigPath re-mints the org-fs mount config, whose API key Better Auth
 * deletes at expiry, before a persisted config is replayed.
 */
export const OrgFsConfigPath = "/api/_sandbox-controller/org-fs-config";

export interface OrgFsConfigRequest {
  tenant: Tenant;
}

export interface OrgFsConfigResponse {
  /** Null when Studio cannot mint; the controller keeps the config it has. */
  orgFsConfigJson: string | null;
}
