#!/usr/bin/env bun
/**
 * First-time setup for local development.
 *
 * Resolves MESH_HOME, generates secrets, and writes a `.env` file so that
 * `bun run dev` picks up the correct environment without any wrapper script.
 *
 * Usage:
 *   bun run setup              # Interactive — prompts for MESH_HOME on first run
 *   MESH_HOME=~/my-mesh bun run setup   # Explicit path
 */

import { join } from "path";
import { homedir } from "os";

import { ansi, loadOrCreateSecrets, resolveMeshHome } from "./bootstrap";

const meshAppDir = join(import.meta.dir, "..");
const userHome = join(homedir(), "deco");
const ciHome = join(meshAppDir, ".mesh-dev");

// ============================================================================
// Resolve MESH_HOME
// ============================================================================

const meshHome = await resolveMeshHome({
  explicit: process.env.MESH_HOME,
  defaultPath: userHome,
  ciFallback: ciHome,
  banner: `${ansi.bold}${ansi.cyan}Deco Studio${ansi.reset} ${ansi.dim}(setup)${ansi.reset}`,
});

// ============================================================================
// Generate or load secrets
// ============================================================================

const { secrets } = await loadOrCreateSecrets(meshHome);

// ============================================================================
// Write .env file for dev:server (bun --env-file=.env)
// ============================================================================

const envLines = [
  `# Generated by 'bun run setup' — do not commit`,
  `MESH_HOME=${meshHome}`,
  `DATABASE_URL=file:${join(meshHome, "mesh.db")}`,
  `MESH_LOCAL_MODE=true`,
];

if (secrets.BETTER_AUTH_SECRET) {
  envLines.push(`BETTER_AUTH_SECRET=${secrets.BETTER_AUTH_SECRET}`);
}
if (secrets.ENCRYPTION_KEY) {
  envLines.push(`ENCRYPTION_KEY=${secrets.ENCRYPTION_KEY}`);
}

const envPath = join(meshAppDir, ".env");
await Bun.write(envPath, envLines.join("\n") + "\n");

// ============================================================================
// Done
// ============================================================================

const displayHome = meshHome.replace(homedir(), "~");
console.log("");
console.log(`${ansi.green}Setup complete.${ansi.reset}`);
console.log("");
console.log(`  Home:      ${ansi.dim}${displayHome}/${ansi.reset}`);
console.log(`  Secrets:   ${ansi.dim}${displayHome}/secrets.json${ansi.reset}`);
console.log(`  Env file:  ${ansi.dim}apps/mesh/.env${ansi.reset}`);
console.log("");
console.log(
  `Run ${ansi.bold}bun run dev${ansi.reset} to start the dev server.`,
);
console.log("");
