//! The per-sandbox view onto the shared org filesystem.
//!
//! The org's volumes are mounted ONCE per organization under
//! `<account-root>/orgs/<org_slug>/`, not once per sandbox: they are org-wide
//! inside one authenticated account, so mounting per sandbox would run N
//! copies of rclone serving identical content. Each sandbox in that account
//! then gets a cheap symlink view:
//!
//! ```text
//! <account-root>/orgs/<slug>/{home,public,uploads,outputs}   ← the mounts
//! <account-root>/worktrees/<handle>/org/home    -> ../../../orgs/<slug>/home
//! <account-root>/worktrees/<handle>/org/public  -> ../../../orgs/<slug>/public
//! <account-root>/worktrees/<handle>/org/uploads -> ../../../orgs/<slug>/uploads
//! <account-root>/worktrees/<handle>/org/outputs -> ../../../orgs/<slug>/outputs
//! ```
//!
//! ## Why `org` is a SIBLING of `repo`, never inside it
//!
//! The agent's cwd is `<sandbox>/repo` (the git worktree). Putting the org
//! tree inside it would place a network mount under the directory that
//! `bun install`, the dev server, and every git command walk — so a stalled
//! mount could wedge the whole setup pipeline. As a sibling it cannot: the
//! agent reaches it by absolute path (supplied in the harness prompt), and
//! nothing enters the worktree, so unlike the old `decocms link` design there
//! is no `.git/info/exclude` entry to maintain either.
//!
//! ## Why the targets are created even when nothing is mounted
//!
//! A symlink to a missing directory is worse than an empty one: `ls` fails
//! instead of returning nothing, and the agent reports an error rather than
//! "no files". Creating the target directories keeps a mountless sandbox
//! readable-but-empty, which is the agreed degradation, and costs nothing
//! when the mount later lands on top of the same path.

use std::path::{Path, PathBuf};

use super::account_storage::AccountStorage;

/// The volume directories a sandbox sees under `org/`.
///
/// Named for the volumes themselves rather than the old daemon's per-run
/// `upload`/`output` symlinks: narrowing to one thread now happens in the
/// harness prompt (which names `uploads/<threadId>/` directly), so there is no
/// per-dispatch relinking and no race between two runs sharing a sandbox.
pub const ORG_VOLUMES: [&str; 4] = ["home", "public", "uploads", "outputs"];

/// Volumes the desktop must never write to: the org's curated `public`
/// volume and the `public-<set>` volumes generated by the org's public-set
/// sync (`file-storage/public-sets.ts`) — a write there would be silently
/// clobbered by the next sync.
///
/// ONE predicate for both enforcement layers on purpose: the WebDAV surface
/// rejects the write verb (never trusting rclone's `--read-only` flag), and
/// the mount manager additionally mounts read-only. The two layers once
/// carried separate copies that drifted — the mount side matched the bare
/// prefix `public`, which also captures a writable volume named
/// `publications`. Exactly `public` or a `public-` set, nothing looser.
pub(crate) fn is_read_only_volume(volume: &str) -> bool {
    volume == "public" || volume.starts_with("public-")
}

/// `<account-root>/orgs/<org_slug>` — where an organization's volumes mount.
///
/// Returns `None` for a slug that could escape the store or collapse two orgs
/// onto one directory, or when the authenticated account root no longer
/// verifies. The upstream subject is never accepted as a path component;
/// [`AccountStorage`] owns the opaque account directory.
pub(crate) fn org_mount_root(storage: &AccountStorage, org_slug: &str) -> Option<PathBuf> {
    let root = verified_org_mount_path(storage, org_slug).ok()??;
    match std::fs::symlink_metadata(&root) {
        Ok(metadata) if !metadata.file_type().is_dir() || metadata.file_type().is_symlink() => None,
        Ok(_) => Some(root),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Some(root),
        Err(_) => None,
    }
}

/// Create and return the verified organization root for a direct terminal
/// cwd. This deliberately stops at `<account-root>/orgs/<slug>`: terminal
/// launch must not manufacture volume directories or mount ownership.
///
/// `Ok(None)` means the slug is not one safe path segment. Storage/marker and
/// filesystem failures stay distinguishable as `Err` so callers fail closed.
pub(crate) async fn ensure_org_mount_root(
    storage: &AccountStorage,
    org_slug: &str,
) -> std::io::Result<Option<PathBuf>> {
    let Some(root) = verified_org_mount_path(storage, org_slug).map_err(std::io::Error::other)?
    else {
        return Ok(None);
    };
    ensure_real_directory(&root).await?;
    // Re-open every account-owned ancestor after the async create. This
    // catches a marker or directory substitution before publishing the cwd.
    let Some(reverified) =
        verified_org_mount_path(storage, org_slug).map_err(std::io::Error::other)?
    else {
        return Ok(None);
    };
    if reverified != root {
        return Err(std::io::Error::other(
            "org-fs root changed while it was being created",
        ));
    }
    ensure_real_directory(&root).await?;
    Ok(Some(root))
}

fn verified_org_mount_path(
    storage: &AccountStorage,
    org_slug: &str,
) -> Result<Option<PathBuf>, String> {
    storage.verify()?;
    let Some(org_slug) = safe_segment(org_slug) else {
        return Ok(None);
    };
    let orgs_root = storage.orgs_root()?;
    Ok(contained_join(storage.root(), &orgs_root, org_slug))
}

/// `<account-root>/worktrees/<handle>/org` — the sandbox's view directory.
pub(crate) fn sandbox_org_dir(storage: &AccountStorage, handle: &str) -> Option<PathBuf> {
    storage.verify().ok()?;
    let view = storage
        .worktree_root(safe_handle(handle)?)
        .ok()?
        .join("org");
    view.starts_with(storage.root()).then_some(view)
}

/// Create (or repair) the sandbox's `org/` view for `org_slug`.
///
/// Idempotent: re-running replaces links that point somewhere else and leaves
/// correct ones alone, so a sandbox that changes org — or one whose view was
/// partially created before a crash — converges rather than failing.
///
/// Best-effort by design. A sandbox whose org view cannot be built still runs;
/// the agent simply has no org filesystem, which is the same outcome as a
/// failed mount. Returns whether the full view is in place, so the caller can
/// report it.
pub(crate) async fn ensure_org_view(
    storage: &AccountStorage,
    handle: &str,
    org_slug: &str,
) -> bool {
    let (Some(mount_root), Some(view)) = (
        org_mount_root(storage, org_slug),
        sandbox_org_dir(storage, handle),
    ) else {
        tracing::warn!(
            account_id = storage.id(),
            handle,
            org_slug,
            "refusing to build an unsafe org view path"
        );
        return false;
    };

    if let Err(error) = ensure_real_directory(&view).await {
        tracing::warn!(%error, ?view, "failed to create the sandbox org view dir");
        return false;
    }

    if let Err(error) = ensure_real_directory(&mount_root).await {
        tracing::warn!(%error, ?mount_root, "failed to create the account org mount root");
        return false;
    }

    let mut complete = true;
    for volume in ORG_VOLUMES {
        let target = mount_root.join(volume);
        // Create the mount point BEFORE linking so the link resolves to an
        // empty directory rather than dangling (see this module's doc).
        if let Err(error) = ensure_real_directory(&target).await {
            tracing::warn!(%error, ?target, "failed to create the org mount point");
            complete = false;
            continue;
        }
        if !link_volume(storage.root(), &view.join(volume), &target).await {
            complete = false;
        }
    }
    complete
}

pub(super) async fn ensure_real_directory(path: &Path) -> std::io::Result<()> {
    match tokio::fs::symlink_metadata(path).await {
        Ok(metadata) => {
            if !metadata.file_type().is_dir() || metadata.file_type().is_symlink() {
                return Err(std::io::Error::other(format!(
                    "org-fs path is not a real directory: {path:?}"
                )));
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            match tokio::fs::create_dir(path).await {
                Ok(()) => {}
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {}
                Err(error) => return Err(error),
            }
            let metadata = tokio::fs::symlink_metadata(path).await?;
            if !metadata.file_type().is_dir() || metadata.file_type().is_symlink() {
                return Err(std::io::Error::other(format!(
                    "org-fs path is not a real directory: {path:?}"
                )));
            }
        }
        Err(error) => return Err(error),
    }
    Ok(())
}

/// Point `link` at `target`, replacing whatever is there if it disagrees.
///
/// The link is RELATIVE so the whole tree survives being moved (an app-support
/// directory can be migrated between machines or restored from a backup).
async fn link_volume(app_root: &Path, link: &Path, target: &Path) -> bool {
    let Some(relative) = relative_link(app_root, link, target) else {
        tracing::warn!(?link, ?target, "org view link is not under the app root");
        return false;
    };
    // `read_link` (not `metadata`) so a link pointing at a not-yet-mounted
    // path still compares equal instead of looking broken.
    if tokio::fs::read_link(link).await.ok().as_deref() == Some(relative.as_path()) {
        return true;
    }
    // Anything else occupying the path — a stale link, or a real directory
    // left by an older layout — is replaced rather than worked around.
    if tokio::fs::symlink_metadata(link).await.is_ok() {
        let removed = match tokio::fs::remove_file(link).await {
            Ok(()) => true,
            Err(_) => tokio::fs::remove_dir_all(link).await.is_ok(),
        };
        if !removed {
            tracing::warn!(?link, "could not clear the existing org view entry");
            return false;
        }
    }
    match tokio::fs::symlink(&relative, link).await {
        Ok(()) => true,
        Err(error) => {
            tracing::warn!(%error, ?link, ?relative, "failed to link an org volume");
            false
        }
    }
}

/// The `../`-relative path from `link`'s parent to `target`.
///
/// Both are built from the same `app_root`, so the common prefix IS the app
/// root: climb out of the link's parent back to it, then descend to the
/// target. Expressed that way rather than by counting components, because the
/// component counts of two absolute paths say nothing about their relationship
/// — an earlier version subtracted depths and produced a link one level short.
fn relative_link(app_root: &Path, link: &Path, target: &Path) -> Option<PathBuf> {
    let from = link.parent()?.strip_prefix(app_root).ok()?;
    let to = target.strip_prefix(app_root).ok()?;
    let mut out = PathBuf::new();
    for _ in from.components() {
        out.push("..");
    }
    out.push(to);
    Some(out)
}

/// One path segment that cannot escape its parent.
fn safe_segment(segment: &str) -> Option<&str> {
    if segment.is_empty()
        || segment == "."
        || segment == ".."
        || segment.contains('/')
        || segment.contains('\\')
    {
        return None;
    }
    Some(segment)
}

/// A handle is `<host>/<owner>/<repo>/<branch>` — several path segments, so it
/// cannot go through [`safe_segment`], which exists for single-segment org
/// slugs and rejects the `/` outright. Each segment is still validated on its
/// own, so `..` can never climb out of the worktrees root.
fn safe_handle(handle: &str) -> Option<&str> {
    crate::sandbox::handle_is_path_safe(handle).then_some(handle)
}

/// Join one validated segment beneath an AccountStorage-owned base and prove
/// the resulting lexical path remains inside the verified account root.
fn contained_join(account_root: &Path, base: &Path, segment: &str) -> Option<PathBuf> {
    if !base.starts_with(account_root) {
        return None;
    }
    let joined = base.join(segment);
    joined.starts_with(account_root).then_some(joined)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn storage(app_root: &Path, storage_key: &str) -> AccountStorage {
        AccountStorage::open(app_root, storage_key).expect("account storage")
    }

    /// Pins the shared read-only vocabulary for BOTH enforcement layers
    /// (WebDAV write refusal and the `--read-only` mount flag) — including
    /// the `publications` case the drifted mount-side prefix match got wrong.
    #[test]
    fn only_public_and_public_sets_are_read_only() {
        assert!(is_read_only_volume("public"));
        assert!(is_read_only_volume("public-skills"));
        assert!(is_read_only_volume("public-core"));
        for writable in ["home", "uploads", "outputs", "publications"] {
            assert!(
                !is_read_only_volume(writable),
                "{writable} must stay writable"
            );
        }
    }

    #[test]
    fn refuses_slugs_and_handles_that_would_escape() {
        let root = tempfile::tempdir().expect("tempdir");
        let storage = storage(root.path(), "https://studio.example\0subject-a");
        for bad in ["", ".", "..", "a/b", "a\\b"] {
            assert_eq!(org_mount_root(&storage, bad), None, "slug {bad:?}");
        }
        // A handle is multi-segment, so `/` is legal in one where it is not
        // legal in an org slug — but a segment that would climb out is not.
        for bad in ["", ".", "..", "a\\b", "a/../b", "a//b"] {
            assert_eq!(sandbox_org_dir(&storage, bad), None, "handle {bad:?}");
        }
        assert_eq!(
            sandbox_org_dir(&storage, "github.com/acme/repo/feat"),
            Some(
                storage
                    .root()
                    .join("worktrees/github.com/acme/repo/feat/org")
            )
        );
        assert_eq!(
            org_mount_root(&storage, "acme"),
            Some(storage.root().join("orgs/acme"))
        );
    }

    #[tokio::test]
    async fn view_links_every_volume_to_the_shared_org_mount() {
        let root = tempfile::tempdir().expect("tempdir");
        let storage = storage(root.path(), "https://studio.example\0subject-view");

        assert!(ensure_org_view(&storage, "h1", "acme").await);

        for volume in ORG_VOLUMES {
            let link = storage.root().join("worktrees/h1/org").join(volume);
            let expected = storage.root().join("orgs/acme").join(volume);
            // Resolves to the shared mount point, and the mount point exists
            // so the agent reads an empty dir rather than hitting ENOENT.
            assert_eq!(
                std::fs::canonicalize(&link).unwrap(),
                std::fs::canonicalize(&expected).unwrap(),
                "{volume} should resolve to the org mount"
            );
            assert!(
                std::fs::read_dir(&link).is_ok(),
                "{volume} should be listable"
            );
        }
    }

    #[tokio::test]
    async fn direct_terminal_root_creates_only_a_verified_org_directory() {
        let root = tempfile::tempdir().expect("tempdir");
        let storage = storage(root.path(), "https://studio.example\0subject-terminal");

        assert!(ensure_org_mount_root(&storage, "../escape")
            .await
            .expect("unsafe slug is not an I/O failure")
            .is_none());
        let org = ensure_org_mount_root(&storage, "acme")
            .await
            .expect("create org root")
            .expect("safe org slug");
        assert_eq!(org, storage.root().join("orgs/acme"));
        assert!(org.is_dir());
        for volume in ORG_VOLUMES {
            assert!(!org.join(volume).exists());
        }
    }

    /// The whole reason the link is relative: an app-support directory that
    /// gets moved or restored from a backup must not break every sandbox.
    /// Also pins the exact shape — an earlier version was one `..` short.
    #[tokio::test]
    async fn links_are_relative_so_the_tree_survives_a_move() {
        let root = tempfile::tempdir().expect("tempdir");
        let storage = storage(root.path(), "https://studio.example\0subject-relative");
        assert!(ensure_org_view(&storage, "h1", "acme").await);

        let target = std::fs::read_link(storage.root().join("worktrees/h1/org/home")).unwrap();
        assert_eq!(target, PathBuf::from("../../../orgs/acme/home"));
    }

    #[tokio::test]
    async fn ensure_is_idempotent_and_repairs_a_wrong_link() {
        let root = tempfile::tempdir().expect("tempdir");
        let storage = storage(root.path(), "https://studio.example\0subject-repair");
        assert!(ensure_org_view(&storage, "h1", "acme").await);
        assert!(
            ensure_org_view(&storage, "h1", "acme").await,
            "re-run is a no-op"
        );

        // Repoint one volume at the wrong org, as a stale view would be.
        let link = storage.root().join("worktrees/h1/org/home");
        std::fs::remove_file(&link).unwrap();
        std::os::unix::fs::symlink("../../../orgs/other/home", &link).unwrap();

        assert!(ensure_org_view(&storage, "h1", "acme").await);
        assert_eq!(
            std::fs::canonicalize(&link).unwrap(),
            std::fs::canonicalize(storage.root().join("orgs/acme/home")).unwrap(),
            "a link pointing at another org must be repaired"
        );
    }

    #[tokio::test]
    async fn identical_handles_in_two_accounts_never_share_an_org_view() {
        let root = tempfile::tempdir().expect("tempdir");
        let a = storage(root.path(), "https://studio.example\0subject-a-isolated");
        let b = storage(root.path(), "https://studio.example\0subject-b-isolated");

        assert!(ensure_org_view(&a, "h1", "acme").await);
        assert!(ensure_org_view(&b, "h1", "acme").await);

        let a_link = a.root().join("worktrees/h1/org/home");
        let b_link = b.root().join("worktrees/h1/org/home");
        assert_ne!(
            std::fs::canonicalize(&a_link).unwrap(),
            std::fs::canonicalize(&b_link).unwrap()
        );
        assert!(std::fs::canonicalize(&a_link)
            .unwrap()
            .starts_with(std::fs::canonicalize(a.root()).unwrap()));
        assert!(std::fs::canonicalize(&b_link)
            .unwrap()
            .starts_with(std::fs::canonicalize(b.root()).unwrap()));
    }

    #[tokio::test]
    async fn a_storage_whose_account_marker_changed_is_rejected() {
        let root = tempfile::tempdir().expect("tempdir");
        let storage = storage(root.path(), "https://studio.example\0subject-marker");
        std::fs::write(
            storage.root().join(".account-scope-v1"),
            b"replacement-account",
        )
        .expect("replace marker");

        assert_eq!(org_mount_root(&storage, "acme"), None);
        assert_eq!(sandbox_org_dir(&storage, "h1"), None);
        assert!(!ensure_org_view(&storage, "h1", "acme").await);
    }

    #[tokio::test]
    async fn a_symlinked_org_slug_is_rejected_without_touching_its_target() {
        let root = tempfile::tempdir().expect("tempdir");
        let outside = tempfile::tempdir().expect("outside");
        let storage = storage(root.path(), "https://studio.example\0subject-org-link");
        let orgs = storage.orgs_root().expect("orgs root");
        std::os::unix::fs::symlink(outside.path(), orgs.join("acme")).expect("org symlink");

        assert_eq!(org_mount_root(&storage, "acme"), None);
        assert!(ensure_org_mount_root(&storage, "acme").await.is_err());
        assert!(!ensure_org_view(&storage, "h1", "acme").await);
        for volume in ORG_VOLUMES {
            assert!(!outside.path().join(volume).exists());
        }
    }

    #[tokio::test]
    async fn a_symlinked_worktree_component_is_rejected_without_touching_its_target() {
        let root = tempfile::tempdir().expect("tempdir");
        let outside = tempfile::tempdir().expect("outside");
        let storage = storage(root.path(), "https://studio.example\0subject-worktree-link");
        let worktree = storage.worktree_root("h1").expect("worktree root");
        std::fs::remove_dir(&worktree).expect("remove real worktree");
        std::os::unix::fs::symlink(outside.path(), &worktree).expect("worktree symlink");

        assert_eq!(sandbox_org_dir(&storage, "h1"), None);
        assert!(!ensure_org_view(&storage, "h1", "acme").await);
        assert!(!outside.path().join("org").exists());
    }
}
