import { z } from "zod";
import type { ZodType } from "zod";
import type { ToolBinder } from "../core/binder";

/**
 * Collection Bindings
 *
 * This module provides standardized tool bindings for Collections, representing
 * SQL table-like structures with CRUD + Search operations compatible with TanStack DB.
 *
 * Key Features:
 * - Generic collection bindings that work with any entity type
 * - Standardized tool naming: `{COLLECTION}_*`
 * - Compatible with TanStack DB query-collection
 * - Full TypeScript support with proper type constraints
 * - Support for filtering, sorting, and pagination
 * - Simple id and title fields for human-readable identification
 */

/**
 * Base schema for collection entities
 * All collection entities must have an id, title, and audit trail fields
 */
export const BaseCollectionEntitySchema = z.object({
  id: z.string().describe("Unique identifier for the entity"),
  title: z.string().describe("Human-readable title for the entity"),
  description: z.string().nullish().describe("Description of the entity"),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  created_by: z.string().optional(),
  updated_by: z.string().optional(),
});

/**
 * Type helper for BaseCollectionEntitySchema
 */
export type BaseCollectionEntitySchemaType = typeof BaseCollectionEntitySchema;

/**
 * Comparison expression schema for filtering
 */
const ComparisonExpressionSchema = z.object({
  field: z.array(z.string()),
  operator: z.enum(["eq", "gt", "gte", "lt", "lte", "in", "like", "contains"]),
  value: z.unknown(),
});

/**
 * Where expression type for filtering
 * Recursive to allow nested logical operators
 */
export type WhereExpression =
  | z.infer<typeof ComparisonExpressionSchema>
  | {
      operator: "and" | "or" | "not";
      conditions: WhereExpression[];
    };

/**
 * Where expression schema for filtering
 * Supports TanStack DB predicate push-down patterns
 * Recursive to allow nested logical operators
 */
export const WhereExpressionSchema: z.ZodType<WhereExpression> = z.lazy(() =>
  z.union([
    ComparisonExpressionSchema,
    z.object({
      operator: z.enum(["and", "or", "not"]),
      conditions: z.array(WhereExpressionSchema),
    }),
  ]),
);

/**
 * Order by expression for sorting
 */
export const OrderByExpressionSchema = z.object({
  field: z.array(z.string()),
  direction: z.enum(["asc", "desc"]),
  nulls: z.enum(["first", "last"]).optional(),
});

/**
 * Sort preset type for collection queries
 */
export const SortPresetSchema = z
  .enum(["newest", "oldest", "a-z", "z-a"])
  .describe("Sort preset: newest/oldest by updated_at, a-z/z-a by title");

export type SortPreset = z.infer<typeof SortPresetSchema>;

/**
 * List/Query input schema for collections
 * Compatible with TanStack DB LoadSubsetOptions
 */
export const CollectionListInputSchema = z.object({
  search: z
    .string()
    .optional()
    .describe("Search by title and description (case-insensitive)"),
  sort: SortPresetSchema.optional(),
  where: WhereExpressionSchema.optional().describe("Filter expression"),
  orderBy: z
    .array(OrderByExpressionSchema)
    .optional()
    .describe("Sort expressions"),
  limit: z
    .number()
    .int()
    .min(1)
    .max(1000)
    .optional()
    .describe("Maximum number of items to return"),
  offset: z
    .number()
    .int()
    .min(0)
    .optional()
    .describe("Number of items to skip"),
});

/**
 * Factory function to create list output schema for a specific collection type
 */
export function createCollectionListOutputSchema<T extends z.ZodTypeAny>(
  entitySchema: T,
) {
  return z.object({
    items: z.array(entitySchema).describe("Array of collection items"),
    totalCount: z
      .number()
      .int()
      .min(0)
      .optional()
      .describe("Total number of matching items (if available)"),
    hasMore: z
      .boolean()
      .optional()
      .describe("Whether there are more items available"),
  });
}

/**
 * Get by ID input schema
 */
export const CollectionGetInputSchema = z.object({
  id: z.string().describe("ID of the entity to retrieve"),
});

/**
 * Factory function to create get output schema
 */
export function createCollectionGetOutputSchema<T extends z.ZodTypeAny>(
  entitySchema: T,
) {
  return z.object({
    item: entitySchema
      .nullable()
      .describe("The retrieved item, or null if not found"),
  });
}

/**
 * Factory function to create insert input schema
 */
export function createCollectionInsertInputSchema<
  T extends z.ZodObject<z.ZodRawShape>,
>(entitySchema: T) {
  // Remove id field since it may be auto-generated by the server
  return z.object({
    data: entitySchema
      .partial()
      .describe("Data for the new entity (id may be auto-generated)"),
  });
}

/**
 * Factory function to create insert output schema
 */
export function createCollectionInsertOutputSchema<T extends z.ZodTypeAny>(
  entitySchema: T,
) {
  return z.object({
    item: entitySchema.describe("The created entity with generated id"),
  });
}

/**
 * Factory function to create update input schema
 */
export function createCollectionUpdateInputSchema<T extends z.ZodTypeAny>(
  entitySchema: T,
) {
  return z.object({
    id: z.string().describe("ID of the entity to update"),
    data: (entitySchema as unknown as z.ZodObject<z.ZodRawShape>)
      .partial()
      .describe("Partial entity data to update"),
  });
}

/**
 * Factory function to create update output schema
 */
export function createCollectionUpdateOutputSchema<T extends z.ZodTypeAny>(
  entitySchema: T,
) {
  return z.object({
    item: entitySchema.describe("The updated entity"),
  });
}

/**
 * Delete input schema
 */
export const CollectionDeleteInputSchema = z.object({
  id: z.string().describe("ID of the entity to delete"),
});

/**
 * Factory function to create delete output schema
 */
export function createCollectionDeleteOutputSchema<T extends z.ZodTypeAny>(
  entitySchema: T,
) {
  return z.object({
    item: entitySchema.describe("The deleted entity"),
  });
}

/**
 * Options for creating collection bindings
 */
export interface CollectionBindingOptions {
  /**
   * If true, only LIST and GET operations will be included (read-only collection)
   * @default false
   */
  readOnly?: boolean;
}

/**
 * Creates generic collection bindings for a specific entity type
 *
 * This function generates standardized tool bindings that work with any collection/table
 * by accepting a custom entity schema and collection name. The bindings provide:
 * - {NAME}_LIST - Query/search entities with filtering and sorting (required)
 * - {NAME}_GET - Get a single entity by ID (required)
 * - {NAME}_CREATE - Create a new entity (optional, excluded if readOnly=true)
 * - {NAME}_UPDATE - Update an existing entity (optional, excluded if readOnly=true)
 * - {NAME}_DELETE - Delete an entity (optional, excluded if readOnly=true)
 *
 * @param collectionName - The name of the collection/table (e.g., "users", "products", "orders")
 * @param entitySchema - The Zod schema for the entity type (must extend BaseCollectionEntitySchema)
 * @param options - Optional configuration for the collection bindings
 * @returns Array of tool bindings for Collection CRUD + Query operations
 *
 * @example
 * ```typescript
 * const UserSchema = z.object({
 *   id: z.string(),
 *   title: z.string(),
 *   created_at: z.string().datetime(),
 *   updated_at: z.string().datetime(),
 *   created_by: z.string().optional(),
 *   updated_by: z.string().optional(),
 *   email: z.string().email(),
 * });
 *
 * // Full CRUD collection
 * const USER_COLLECTION_BINDING = createCollectionBindings("users", UserSchema);
 *
 * // Read-only collection (only LIST and GET)
 * const READONLY_COLLECTION_BINDING = createCollectionBindings("products", ProductSchema, { readOnly: true });
 * ```
 */
export function createCollectionBindings<
  TEntitySchema extends z.ZodObject<z.ZodRawShape>,
  TName extends string,
>(
  collectionName: TName,
  entitySchema: TEntitySchema,
  options?: CollectionBindingOptions,
) {
  const upperName = collectionName.toUpperCase() as Uppercase<TName>;
  const readOnly = options?.readOnly ?? false;

  const bindings: ToolBinder[] = [
    {
      name: `${upperName}_LIST` as const,
      inputSchema: CollectionListInputSchema,
      outputSchema: createCollectionListOutputSchema(entitySchema),
    },
    {
      name: `${upperName}_GET` as const,
      inputSchema: CollectionGetInputSchema,
      outputSchema: createCollectionGetOutputSchema(entitySchema),
    },
  ];

  // Only include mutation operations if not read-only
  if (!readOnly) {
    bindings.push(
      {
        name: `${upperName}_CREATE` as const,
        inputSchema: createCollectionInsertInputSchema(entitySchema),
        outputSchema: createCollectionInsertOutputSchema(entitySchema),
        opt: true,
      },
      {
        name: `${upperName}_UPDATE` as const,
        inputSchema: createCollectionUpdateInputSchema(entitySchema),
        outputSchema: createCollectionUpdateOutputSchema(entitySchema),
        opt: true,
      },
      {
        name: `${upperName}_DELETE` as const,
        inputSchema: CollectionDeleteInputSchema,
        outputSchema: createCollectionDeleteOutputSchema(entitySchema),
        opt: true,
      },
    );
  }

  return bindings as unknown as CollectionBinding<
    TEntitySchema,
    Uppercase<TName>
  >;
}

// Helper type for tool definition
type ToolBinding<
  Name extends string,
  Input,
  Output,
  Opt extends boolean = false,
> = {
  name: Name;
  inputSchema: ZodType<Input>;
  outputSchema: ZodType<Output>;
} & (Opt extends true ? { opt: true } : unknown);

/**
 * Type helper to extract the collection binding type
 */
export type CollectionBinding<
  TEntitySchema,
  TUpperName extends Uppercase<string> = Uppercase<string>,
  TEntity = TEntitySchema extends z.ZodObject<z.ZodRawShape>
    ? z.infer<TEntitySchema>
    : TEntitySchema,
> = [
  ToolBinding<
    `${TUpperName}_LIST`,
    CollectionListInput,
    CollectionListOutput<TEntity>
  >,
  ToolBinding<
    `${TUpperName}_GET`,
    CollectionGetInput,
    CollectionGetOutput<TEntity>
  >,
  ToolBinding<
    `${TUpperName}_CREATE`,
    CollectionInsertInput<TEntity>,
    CollectionInsertOutput<TEntity>,
    true
  >,
  ToolBinding<
    `${TUpperName}_UPDATE`,
    CollectionUpdateInput<TEntity>,
    CollectionUpdateOutput<TEntity>,
    true
  >,
  ToolBinding<
    `${TUpperName}_DELETE`,
    CollectionDeleteInput,
    CollectionDeleteOutput<TEntity>,
    true
  >,
];

/**
 * Type helper to extract tool names from a collection binding
 */
export type CollectionTools<
  TEntitySchema extends z.ZodObject<z.ZodRawShape>,
  TUpperName extends Uppercase<string> = Uppercase<string>,
> = CollectionBinding<TEntitySchema, TUpperName>[number]["name"];

// Export types for TypeScript usage
export type CollectionListInput = z.infer<typeof CollectionListInputSchema>;
export type CollectionGetInput = z.infer<typeof CollectionGetInputSchema>;
export type CollectionDeleteInput = z.infer<typeof CollectionDeleteInputSchema>;
export type OrderByExpression = z.infer<typeof OrderByExpressionSchema>;

/**
 * Type helper for insert input with generic item type
 */
export type CollectionInsertInput<T> = {
  data: Partial<T>;
};

/**
 * Type helper for update input with generic item type
 */
export type CollectionUpdateInput<T> = {
  id: string;
  data: Partial<T>;
};

/**
 * Type helper for list output with generic item type
 */
export type CollectionListOutput<T> = {
  items: T[];
  totalCount?: number;
  hasMore?: boolean;
};

/**
 * Type helper for get output with generic item type
 */
export type CollectionGetOutput<T> = {
  item: T | null;
};

/**
 * Type helper for insert output with generic item type
 */
export type CollectionInsertOutput<T> = {
  item: T;
};

/**
 * Type helper for update output with generic item type
 */
export type CollectionUpdateOutput<T> = {
  item: T;
};

/**
 * Type helper for delete output with generic item type
 */
export type CollectionDeleteOutput<T> = {
  item: T;
};

/**
 * Base collection entity type - inferred from BaseCollectionEntitySchema
 */
export type BaseCollectionEntity = z.infer<typeof BaseCollectionEntitySchema>;

// ---------------------------------------------------------------------------
// Shared utilities for resolving simple params and in-memory filtering/sorting
// ---------------------------------------------------------------------------

/**
 * Map a sort preset to an OrderByExpression
 */
const SORT_PRESET_MAP: Record<SortPreset, OrderByExpression> = {
  newest: { field: ["updated_at"], direction: "desc" },
  oldest: { field: ["updated_at"], direction: "asc" },
  "a-z": { field: ["title"], direction: "asc" },
  "z-a": { field: ["title"], direction: "desc" },
};

/**
 * Resolve the simple `search` and `sort` params into the canonical
 * `where` / `orderBy` fields, merging with any explicit values.
 *
 * - `search` → OR-contains across `searchFields`, AND-ed with existing `where`
 * - `sort`   → mapped to `orderBy`; explicit `orderBy` takes precedence
 */
export function resolveCollectionListInput(
  input: CollectionListInput,
  searchFields: string[] = ["title", "description"],
): {
  where?: WhereExpression;
  orderBy?: OrderByExpression[];
  limit?: number;
  offset?: number;
} {
  let where: WhereExpression | undefined = input.where;

  // Build search where clause
  if (input.search?.trim()) {
    const term = input.search.trim();
    const searchConditions: WhereExpression[] = searchFields.map((field) => ({
      field: [field],
      operator: "contains" as const,
      value: term,
    }));

    const searchWhere: WhereExpression =
      searchConditions.length === 1
        ? searchConditions[0]!
        : { operator: "or" as const, conditions: searchConditions };

    // AND with existing where
    where = where
      ? { operator: "and" as const, conditions: [where, searchWhere] }
      : searchWhere;
  }

  // Resolve orderBy: explicit orderBy wins, then sort preset
  const orderBy =
    input.orderBy ?? (input.sort ? [SORT_PRESET_MAP[input.sort]] : undefined);

  return {
    ...(where && { where }),
    ...(orderBy && { orderBy }),
    ...(input.limit != null && { limit: input.limit }),
    ...(input.offset != null && { offset: input.offset }),
  };
}

/**
 * Convert SQL LIKE pattern to regex pattern by tokenizing.
 * Handles % (any chars) and _ (single char) wildcards.
 */
function convertLikeToRegex(likePattern: string): string {
  const result: string[] = [];
  for (let i = 0; i < likePattern.length; i++) {
    const char = likePattern[i] as string;
    if (char === "%") {
      result.push(".*");
    } else if (char === "_") {
      result.push(".");
    } else if (/[.*+?^${}()|[\]\\]/.test(char)) {
      result.push("\\" + char);
    } else {
      result.push(char);
    }
  }
  return result.join("");
}

function isStringOrNumber(value: unknown): value is string | number {
  return typeof value === "string" || typeof value === "number";
}

/**
 * Get a nested field value from an object using a dot-separated path.
 */
function getFieldValue(
  entity: Record<string, unknown>,
  fieldPath: string,
): unknown {
  const parts = fieldPath.split(".");
  let value: unknown = entity;
  for (const part of parts) {
    if (value == null || typeof value !== "object") return undefined;
    value = (value as Record<string, unknown>)[part];
  }
  return value;
}

/**
 * Evaluate a WhereExpression against an entity object in memory.
 */
export function evaluateWhereExpression(
  entity: Record<string, unknown>,
  where: WhereExpression,
): boolean {
  if ("conditions" in where) {
    const { operator, conditions } = where;
    switch (operator) {
      case "and":
        return conditions.every((c) => evaluateWhereExpression(entity, c));
      case "or":
        return conditions.some((c) => evaluateWhereExpression(entity, c));
      case "not":
        return !conditions.every((c) => evaluateWhereExpression(entity, c));
      default:
        return true;
    }
  }

  const { field, operator, value } = where;
  const fieldPath = field.join(".");
  const fieldValue = getFieldValue(entity, fieldPath);

  switch (operator) {
    case "eq":
      return fieldValue === value;
    case "gt":
      return (
        isStringOrNumber(fieldValue) &&
        isStringOrNumber(value) &&
        fieldValue > value
      );
    case "gte":
      return (
        isStringOrNumber(fieldValue) &&
        isStringOrNumber(value) &&
        fieldValue >= value
      );
    case "lt":
      return (
        isStringOrNumber(fieldValue) &&
        isStringOrNumber(value) &&
        fieldValue < value
      );
    case "lte":
      return (
        isStringOrNumber(fieldValue) &&
        isStringOrNumber(value) &&
        fieldValue <= value
      );
    case "in":
      return Array.isArray(value) && value.includes(fieldValue);
    case "like":
      if (typeof fieldValue !== "string" || typeof value !== "string") {
        return false;
      }
      if (value.length > 100) return false;
      return new RegExp(`^${convertLikeToRegex(value)}$`, "i").test(fieldValue);
    case "contains":
      if (typeof fieldValue !== "string" || typeof value !== "string") {
        return false;
      }
      return fieldValue.toLowerCase().includes(value.toLowerCase());
    default:
      return true;
  }
}

/**
 * Sort an array of entities by OrderByExpression list (in memory).
 */
export function applyOrderBy<T extends Record<string, unknown>>(
  items: T[],
  orderBy: OrderByExpression[],
): T[] {
  return [...items].sort((a, b) => {
    for (const order of orderBy) {
      const fieldPath = order.field.join(".");
      const aValue = getFieldValue(a, fieldPath);
      const bValue = getFieldValue(b, fieldPath);

      let comparison = 0;

      if (aValue == null && bValue == null) continue;
      if (aValue == null) {
        comparison = order.nulls === "first" ? -1 : 1;
      } else if (bValue == null) {
        comparison = order.nulls === "first" ? 1 : -1;
      } else if (typeof aValue === "string" && typeof bValue === "string") {
        comparison = aValue.localeCompare(bValue);
      } else if (typeof aValue === "number" && typeof bValue === "number") {
        comparison = aValue - bValue;
      } else {
        comparison = String(aValue).localeCompare(String(bValue));
      }

      if (comparison !== 0) {
        return order.direction === "desc" ? -comparison : comparison;
      }
    }
    return 0;
  });
}
