package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// apiTypes renders every exported declaration of the Go package in dir, in
// source order: a struct becomes an interface (a field is optional when its
// tag says omitempty or omitzero; a pointer that is not optional is
// `T | null`), a string type becomes the union of its typed constants, and an
// untyped string constant stays a constant. Comments carry over.
func apiTypes(dir string) (string, error) {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}
	var names []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".go") && !strings.HasSuffix(e.Name(), "_test.go") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	var files []*ast.File
	for _, name := range names {
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return "", err
		}
		files = append(files, f)
	}

	// Typed constants, by type, for the unions.
	enums := map[string][]enumValue{}
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs := spec.(*ast.ValueSpec)
				typ, ok := vs.Type.(*ast.Ident)
				if !ok {
					continue
				}
				for _, v := range vs.Values {
					if lit, ok := v.(*ast.BasicLit); ok && lit.Kind == token.STRING {
						enums[typ.Name] = append(enums[typ.Name], enumValue{lit.Value, docText(vs.Doc)})
					}
				}
			}
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by packages/sandbox/controller-go/cmd/tsgen from the controller's protocol package.\n// Do not edit; run `go generate ./...` in packages/sandbox/controller-go.\n")
	for _, f := range files {
		if f.Doc != nil {
			fmt.Fprintf(&b, "\n%s", jsdoc(f.Doc.Text(), ""))
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range gd.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if !s.Name.IsExported() {
						continue
					}
					doc := s.Doc
					if doc == nil && len(gd.Specs) == 1 {
						doc = gd.Doc
					}
					out, err := renderType(s, doc, enums)
					if err != nil {
						return "", err
					}
					b.WriteString("\n" + out)
				case *ast.ValueSpec:
					if gd.Tok != token.CONST || s.Type != nil {
						continue
					}
					for i, name := range s.Names {
						lit, ok := s.Values[i].(*ast.BasicLit)
						if !name.IsExported() || !ok || lit.Kind != token.STRING {
							continue
						}
						doc := s.Doc
						if doc == nil && len(gd.Specs) == 1 {
							doc = gd.Doc
						}
						fmt.Fprintf(&b, "\n%sexport const %s = %s;\n", jsdoc(docText(doc), ""), name.Name, lit.Value)
					}
				}
			}
		}
	}
	return b.String(), nil
}

func docText(g *ast.CommentGroup) string {
	if g == nil {
		return ""
	}
	return g.Text()
}

func jsdoc(text, pad string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return ""
	}
	lines := strings.Split(text, "\n")
	if len(lines) == 1 {
		return fmt.Sprintf("%s/** %s */\n", pad, lines[0])
	}
	var b strings.Builder
	b.WriteString(pad + "/**\n")
	for _, l := range lines {
		if l == "" {
			b.WriteString(pad + " *\n")
		} else {
			b.WriteString(pad + " * " + l + "\n")
		}
	}
	b.WriteString(pad + " */\n")
	return b.String()
}

type enumValue struct{ literal, doc string }

func renderType(s *ast.TypeSpec, doc *ast.CommentGroup, enums map[string][]enumValue) (string, error) {
	head := jsdoc(docText(doc), "")
	switch t := s.Type.(type) {
	case *ast.StructType:
		var extends []string
		var body strings.Builder
		for _, field := range t.Fields.List {
			name, opts := jsonName(field)
			if name == "-" {
				continue
			}
			if len(field.Names) == 0 {
				embedded, err := tsType(field.Type, false)
				if err != nil {
					return "", err
				}
				extends = append(extends, embedded)
				continue
			}
			if !field.Names[0].IsExported() {
				continue
			}
			if name == "" {
				name = field.Names[0].Name
			}
			optional := opts["omitempty"] || opts["omitzero"]
			typ, err := tsType(field.Type, !optional)
			if err != nil {
				return "", fmt.Errorf("%s.%s: %w", s.Name.Name, field.Names[0].Name, err)
			}
			q := ""
			if optional {
				q = "?"
			}
			body.WriteString(jsdoc(docText(field.Doc), "  "))
			fmt.Fprintf(&body, "  %s%s: %s;\n", name, q, typ)
		}
		ext := ""
		if len(extends) > 0 {
			ext = " extends " + strings.Join(extends, ", ")
		}
		return fmt.Sprintf("%sexport interface %s%s {\n%s}\n", head, s.Name.Name, ext, body.String()), nil
	case *ast.Ident:
		if t.Name == "string" {
			if vals := enums[s.Name.Name]; len(vals) > 0 {
				// One line when it fits and nothing is documented, as the repo's
				// formatter would print it.
				literals := make([]string, 0, len(vals))
				documented := false
				for _, v := range vals {
					literals = append(literals, v.literal)
					documented = documented || v.doc != ""
				}
				if line := fmt.Sprintf("export type %s = %s;", s.Name.Name, strings.Join(literals, " | ")); !documented && len(line) <= 80 {
					return head + line + "\n", nil
				}
				var b strings.Builder
				fmt.Fprintf(&b, "%sexport type %s =", head, s.Name.Name)
				for _, v := range vals {
					b.WriteString("\n" + strings.TrimSuffix(jsdoc(v.doc, "  "), "\n"))
					if v.doc != "" {
						b.WriteString("\n")
					}
					b.WriteString("  | " + v.literal)
				}
				b.WriteString(";\n")
				return strings.ReplaceAll(b.String(), "=\n\n", "=\n"), nil
			}
		}
		typ, err := tsType(t, false)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%sexport type %s = %s;\n", head, s.Name.Name, typ), nil
	}
	return "", fmt.Errorf("%s: unsupported declaration", s.Name.Name)
}

func jsonName(f *ast.Field) (string, map[string]bool) {
	opts := map[string]bool{}
	if f.Tag == nil {
		return "", opts
	}
	raw, err := strconv.Unquote(f.Tag.Value)
	if err != nil {
		return "", opts
	}
	parts := strings.Split(reflect.StructTag(raw).Get("json"), ",")
	for _, o := range parts[1:] {
		opts[o] = true
	}
	return parts[0], opts
}

// tsType maps a Go type expression; nullable adds `| null` to a pointer.
func tsType(e ast.Expr, nullable bool) (string, error) {
	switch t := e.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string", nil
		case "bool":
			return "boolean", nil
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
			return "number", nil
		}
		if t.IsExported() {
			return t.Name, nil
		}
	case *ast.StarExpr:
		inner, err := tsType(t.X, false)
		if err != nil {
			return "", err
		}
		if nullable {
			return inner + " | null", nil
		}
		return inner, nil
	case *ast.ArrayType:
		inner, err := tsType(t.Elt, false)
		if err != nil {
			return "", err
		}
		return "Array<" + inner + ">", nil
	case *ast.MapType:
		if k, ok := t.Key.(*ast.Ident); ok && k.Name == "string" {
			inner, err := tsType(t.Value, false)
			if err != nil {
				return "", err
			}
			return "Record<string, " + inner + ">", nil
		}
	}
	return "", fmt.Errorf("unsupported type %T", e)
}
