// Command tsgen writes the TypeScript types in packages/sandbox/controller-types
// from their Go source of truth:
//
//   - tsgen <crd.yaml> <out.ts>: the SandboxVariant CRD, from its generated
//     OpenAPI schema, so the control plane renders against what the API server
//     will validate.
//   - tsgen api <package dir> <out.ts>: the claim API, from the protocol
//     package's declarations (see api.go).
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

func main() {
	switch {
	case len(os.Args) == 4 && os.Args[1] == "api":
		out, err := apiTypes(os.Args[2])
		if err != nil {
			fail(err)
		}
		if err := os.WriteFile(os.Args[3], []byte(out), 0o644); err != nil {
			fail(err)
		}
	case len(os.Args) == 3:
		crdTypes(os.Args[1], os.Args[2])
	default:
		fmt.Fprintln(os.Stderr, "usage: tsgen <crd.yaml> <out.ts> | tsgen api <package dir> <out.ts>")
		os.Exit(2)
	}
}

func crdTypes(crdPath, outPath string) {
	raw, err := os.ReadFile(crdPath)
	if err != nil {
		fail(err)
	}
	var crd apiextensionsv1.CustomResourceDefinition
	if err := yaml.Unmarshal(raw, &crd); err != nil {
		fail(err)
	}
	v := crd.Spec.Versions[0]
	root := v.Schema.OpenAPIV3Schema
	kind := crd.Spec.Names.Kind

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by packages/sandbox/controller-go/cmd/tsgen from the %s CRD.\n// Do not edit; run `go generate ./...` in packages/sandbox/controller-go.\n\n", kind)
	fmt.Fprintf(&b, "export const API_VERSION = %q;\nexport const KIND = %q;\n\n", crd.Spec.Group+"/"+v.Name, kind)
	fmt.Fprintf(&b, "export interface %sSpec %s\n\n", kind, render(root.Properties["spec"], 0))
	fmt.Fprintf(&b, "export interface %sStatus %s\n\n", kind, render(root.Properties["status"], 0))
	fmt.Fprintf(&b, `export interface %[1]s {
  apiVersion: typeof API_VERSION;
  kind: typeof KIND;
  metadata: {
    name: string;
    namespace?: string;
    labels?: Record<string, string>;
    annotations?: Record<string, string>;
  };
  spec: %[1]sSpec;
  status?: %[1]sStatus;
}
`, kind)
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
}

func render(s apiextensionsv1.JSONSchemaProps, depth int) string {
	switch {
	case s.XIntOrString:
		return "number | string"
	case s.Type == "string" && len(s.Enum) > 0:
		var vals []string
		for _, e := range s.Enum {
			vals = append(vals, string(e.Raw))
		}
		return strings.Join(vals, " | ")
	case s.Type == "string":
		return "string"
	case s.Type == "integer", s.Type == "number":
		return "number"
	case s.Type == "boolean":
		return "boolean"
	case s.Type == "array":
		return "Array<" + render(*s.Items.Schema, depth) + ">"
	case s.Type == "object" && len(s.Properties) == 0 && s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil:
		return "Record<string, " + render(*s.AdditionalProperties.Schema, depth) + ">"
	case s.Type == "object" && len(s.Properties) > 0:
		required := map[string]bool{}
		for _, r := range s.Required {
			required[r] = true
		}
		names := make([]string, 0, len(s.Properties))
		for n := range s.Properties {
			names = append(names, n)
		}
		sort.Strings(names)
		pad := strings.Repeat("  ", depth+1)
		var b strings.Builder
		b.WriteString("{\n")
		for _, n := range names {
			p := s.Properties[n]
			if p.Description != "" {
				fmt.Fprintf(&b, "%s/** %s */\n", pad, strings.Join(strings.Fields(p.Description), " "))
			}
			opt := "?"
			if required[n] {
				opt = ""
			}
			fmt.Fprintf(&b, "%s%s%s: %s;\n", pad, n, opt, render(p, depth+1))
		}
		b.WriteString(strings.Repeat("  ", depth) + "}")
		return b.String()
	}
	return "unknown"
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
